---
openapi: 3.0.0
info:
  title: Unofficial Sitecore CDP/Personalize API
  description: This is the unofficial API definition for Sitecore CDP and Personalize, that I use for reference purposes in the community.
  version: 0.0.1
servers:
  - url: https://api-us.boxever.com
  - url: https://api.boxever.com
tags:
  - name: Batch APIs
  - name: Stream / Real-Time APIs
  - name: Interactive / Rest APIs
  - name: Tenant Management
components:
  securitySchemes:
    oAuthCredentials:
      type: oauth2
      description: ''
      flows:
        clientCredentials:
          tokenUrl: /v2/oauth/token
          scopes: {}
    oAuthPassword:
      type: oauth2
      description: ''
      flows:
        password:
          tokenUrl: /v2/oauth/token 
          scopes: {}    
paths:
  /v3/flowDefinitions:
    get:
      tags: [ "Tenant Management|Flows" ]
      summary: ''
      description: ''
      security:
        - oAuthCredentials: []
        - oAuthPassword: []
      parameters:
        - name: expand
          in: query
          description: ''
          required: false
          schema:
            type: boolean
            format: boolean
      responses:
        '200':
          description: ''
  /v2/connections:
    get:
      tags: [ "Tenant Management|Connections"]
      summary: 'Retrieve Connections'
      description: ''
      security:
        - oAuthPassword: []
      responses:
        '200':
          description: ''